### ISSUE TITLE
Iteration over edgeR fails upon changes to metadata.txt

### ISSUE THREAD

**Issue by JuHey** [csoneson/ARMOR#106]
After successful completion of ARMOR run, I changed identifiers outside of 'names' and 'type' in metadata.txt and modified 'design' and 'construct' in config.yaml to reflect those changes. The reason was to add further statistical tests that I had omitted in the first run. Re invoking `snakemake` after dry-run testing led to error in edgeR pointing to unrecognized object name in the 'construct' i.e., as in groupB-N.`Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': object 'N' not found`. It seems that the changes in metadata.txt were not properly implemented. How can I fix this?

**Comment by csoneson** [comment]
First, I'm wondering if the contrast above should really be `groupB-groupN`? 
If that doesn't explain it, I think we need more information to figure it out. What does your metadata file look like, and how did you specify the design and contrast? Did you first run the `checkinputs` rule (see https://github.com/csoneson/ARMOR/wiki/Testing-the-setup)?

**Comment by JuHey** [comment]
May I contact you offline?

**Comment by csoneson** [comment]
For the sake of helping others who may run into a similar problem, I suggest to keep the main discussion here. However, if you are not comfortable sharing your data here, you can either show a mock-up example with the same structure or email me (charlotte.soneson@fmi.ch).

**Comment by JuHey** [comment]
I benefited two ways here: it is important to read the documentation carefully. The `checkinputs` test had escaped me. And secondly, it is in the syntax: I had left out the qualifier for one of the  'groups'. Typical 'cut-and-paste' error. I stand corrected. Thank you for getting me on track! With best wishes and stay safe.
