### ISSUE TITLE
Issues Running Example Dataset

### ISSUE THREAD

**Issue by nicholasgreco** [csoneson/ARMOR#107]
Hello, and sorry for the inconvenience. After cloning the repository and running the command `cd ARMOR && snakemake --use conda`, I receive the following error:

Error: you need to specify the maximum number of CPU cores to be used at the same time. If you want to use N cores, say --cores N or -cN. For all cores on your system (be sure that this is appropriate) use --cores all. For no parallelization use --cores 1 or -c1.

I attempt to set the max core value by typing `snakemake -j 4` and running, but I receive a long-winded error message highlighting errors in the rules fastq and pkginstall.

I am rather new to this all. Do you have any advice on how to solve this?

**Comment by csoneson** [comment]
Could you try `snakemake --use-conda --cores 4`?

**Comment by nicholasgreco** [comment]
Thank you so much. That seemed to work!
