### ISSUE TITLE
column-spillover in DGE result .txt file

### ISSUE THREAD

**Issue by JuHey** [csoneson/ARMOR#109]
DGE output into the edgeR_dge_results.txt file results in column-spillover in the 'tx_ids' column with ENSEMBLE Transcript IDs listed as c("ENSTxxx", ...) over many lines. The entire file structure is compromised, which makes handling the output rather cumbersome especially as the 'tx_ids' fields vary in length and makeup. Is there a way to suppress this behavior?

<img width="1968" alt="Screen Shot 2022-01-05 at 9 40 53 PM" src="https://user-images.githubusercontent.com/36309128/148319703-3e83d377-4f06-4f6a-ba1b-a45004974ac9.png">

Wishing you a Happy New Year!

**Comment by csoneson** [comment]
Thanks for pointing this out. Agreed, it makes more sense to not have this column cluttering the text file output, and I just pushed an update (v1.5.6) that removes it. You can just modify the appropriate lines in your local copy of the `edgeR_dge.Rmd` file: https://github.com/csoneson/ARMOR/blob/bbd031caf1b979c0d9b51ca762d9e6cadfce20e8/scripts/edgeR_dge.Rmd#L276 and https://github.com/csoneson/ARMOR/blob/bbd031caf1b979c0d9b51ca762d9e6cadfce20e8/scripts/edgeR_dge.Rmd#L282
