### ISSUE TITLE
Add 'camera' for gene set testing?

### ISSUE THREAD

**Issue by markrobinsonuzh** [csoneson/ARMOR#11]
- what set of gene sets to use?  MSigDB?
- link to Ensembl identifiers (MSigDB has Entrez ids)
- how to integrate with existing BioC annotation packages

**Comment by csoneson** [comment]
Implemented in d228ae0d8c34373a45db4a7b609698b69faa448d

**Comment by khembach** [comment]
Add the `camera` code to the `edgeR_dge.Rmd` and add a parameter "run_camera" to the `config.yaml` that determines if the `camera` part should be run.

**Comment by markrobinsonuzh** [comment]
Merged https://github.com/csoneson/ARMOR/pull/53
