### ISSUE TITLE
Detailed instructions for MacOS installation?

### ISSUE THREAD

**Issue by devang-mehta** [csoneson/ARMOR#114]
Do you have a more detailed set of instructions to install on MacOS via conda? I have tried to follow the instructions with a separate R install but always have problems with packages not being installed/installable. Linux worked great though!

**Comment by csoneson** [comment]
Could you provide some more details about the errors you get/which packages can not be installed/which R version you have? On my mac, I've set up ARMOR via route '1b' as described in the [wiki](https://github.com/csoneson/ARMOR/wiki/Managing-software). This is also the approach we're using in the [GitHub Actions](https://github.com/csoneson/ARMOR/actions/runs/3443806091/jobs/5745730950) workflow.

**Comment by devang-mehta** [comment]
Yes, I am also trying the 1b method. I first made the changes to `config.yaml` and `.Renviron` according to the instructions here: https://github.com/csoneson/ARMOR/wiki/Managing-software#using-a-system-r-installation

Then I ran `snakemake --use-conda setup --cores 1` and got the following output:

```
Building DAG of jobs...
Creating conda environment envs/environment.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/u0153892/Library/CloudStorage/OneDrive-SharedLibraries-KULeuven/BIOSYST-EPSBLab-General/04_SOFTWARE/ARMOR/envs/environment.yaml:
Command:
mamba env create --quiet --file "/Users/u0153892/Library/CloudStorage/OneDrive-SharedLibraries-KULeuven/BIOSYST-EPSBLab-General/04_SOFTWARE/ARMOR/.snakemake/conda/56816874111d1ac73a41aeef6cac00fa_.yaml" --prefix "/Users/u0153892/Library/CloudStorage/OneDrive-SharedLibraries-KULeuven/BIOSYST-EPSBLab-General/04_SOFTWARE/ARMOR/.snakemake/conda/56816874111d1ac73a41aeef6cac00fa_"
Output:
Encountered problems while solving:
  - nothing provides requested samtools 1.11**
  - nothing provides requested salmon 1.4.0**
  - nothing provides requested star 2.7.7a**
  - nothing provides requested cutadapt 3.2**
  - nothing provides requested bedtools 2.30.0**
  - nothing provides requested ucsc-bedgraphtobigwig 377**
  - nothing provides requested pandoc 2.11**
  - nothing provides cutadapt needed by trim-galore-0.6.6-0
  ```

I have R version 4.2.2.

**Comment by csoneson** [comment]
I'm going to close this issue - feel free to reopen if you have additional/remaining questions.
