### ISSUE TITLE
Apparently stuck when running the example data set

### ISSUE THREAD

**Issue by MDanialSaleem** [csoneson/ARMOR#116]
Hi,

I'd like to preface this with the fact that I am not a bioinformatics person, so I apologize if this is a rather obvious thing.

But when I run the example dataset, it appears to get stuck on 

```
[Mon Feb 26 11:48:32 2024]
Finished job 1.
39 of 46 steps (85%) done
```

with no info printed. 

Is it supposed to take a long time on this step?

Also - how long does the entire workflow take to run in general on the example dataset, for a rough estimate of resources I have: M2 mac with 8 GB of ram.

Thanks.

**Comment by MDanialSaleem** [comment]
That worked, thanks a lot for the prompt reply.

**Comment by csoneson** [comment]
Excellent!
