### ISSUE TITLE
Complete description in Wiki (snakemake installation, any others?)

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#18]
Consider moving instructions from README to a Wiki. The wiki can also include a Methods document, describing the provided workflow in words (with references).

**Comment by sorjuela** [comment]
Should we move Issue#9 to this one?

**Comment by csoneson** [comment]
Yes, seems like a good idea!

**Comment by csoneson** [comment]
I copied most of the current README to the Wiki, and started writing a Method description.

**Comment by sorjuela** [comment]
Order the pages on the right panel (numbering)? 
All give a quick read and spot mistakes, add more explaining text
