### ISSUE TITLE
Vignette of public data set analysis

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#47]
airway data?

**Comment by khembach** [comment]
Include explanations on how to modify the `config.yaml` and `.rmd` files. Include screenshots of the modifications and the output directory.

**Comment by markrobinsonuzh** [comment]
Added Charlotte's `iSEE` script to the repo, so I think everything is now there for the vignette of the public dataset:
https://github.com/csoneson/ARMOR/tree/chiron_realdataworkflow
