### ISSUE TITLE
pandoc

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#55]
Do we need to include pandoc and pandoc-citeproc in the environment file, to make sure that the Rmarkdown files will compile?

**Comment by fionarhuang** [comment]
I am not sure about this. I remember that the workflow had the issue about pandoc version to pass the travis tests some time ago. Does that somehow indicate we should suggest a version of pandoc in the environment file?

**Comment by csoneson** [comment]
currently pandoc and pandoc-citeproc are being explicitly installed for travis, but it might be better to do this in the environments. I guess it would need to be in both the R environment and in the other one, for people who don't want to use the conda R.

**Comment by fionarhuang** [comment]
I simply add pandoc to the two environment files. Not sure how it works, probably Kathi know better about the environment part.

**Comment by csoneson** [comment]
I think we need also `pandoc-citeproc`. And we can remove the installation of these two from the travis file.
