### ISSUE TITLE
groupvar

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#56]
Do we still need the `groupvar` (specified in the config file)? It is only used to create the `bwCond` column of the final SCEs, and in the end any column could be used there.

**Comment by fionarhuang** [comment]
I think we could delete `groupvar`. All columns of metadata.txt are now in the column data of sce. We don't need to create a `bwCond` column anymore.

**Comment by fionarhuang** [comment]
I have updated this part. After it passes the travis CI test, probably we could merge the project and close the issue.

**Comment by csoneson** [comment]
Maybe you already did it, but this needs to also be properly checked locally - travis doesn't test this script (since it takes too long to run everything).

**Comment by khembach** [comment]
Fixed with ce99c66622d2e7d46eb47f45695a297582fa8d97
