### ISSUE TITLE
FASTQ file sample suffix

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#58]
Is it unnecessarily restrictive to assume that FASTQ files are of the form `<sample>_{R1/R2}.fastq.gz`? I.e., should we allow the user to specify the `{R1/R2}` part in the config file (just `{1/2}` is also very common)?

**Comment by csoneson** [comment]
Implemented in fc28fd906efef9f2b117ccddb0c17466f1043def

**Comment by markrobinsonuzh** [comment]
Merged here: https://github.com/csoneson/ARMOR/commit/01fc8b9e92eb54e174fb8d1bbb066a6407f10c95
