### ISSUE TITLE
Clean up `multi_experiment` branch

### ISSUE THREAD

**Issue by markrobinsonuzh** [csoneson/ARMOR#63]
If we want to go this route, we could/should:
- clean up the RMD files to get rid of the XXXX and ******* parts
- expose other variables, like geneset subsets, DRIMSeq filtering to `config.yaml`?
- "arbitrary design and multiple contrasts" ?

https://github.com/csoneson/ARMOR/tree/multi_experiment

**Comment by csoneson** [comment]
Fixed in 779fd127a17fc7c40cf512b89f2ea522f2bf08a0
