### ISSUE TITLE
extend checks of input variables

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#64]
Extend checks of input variables (`design`, `contrast`, etc) in `run_render.R`/`generate_report.R`. In addition to just checking that these are character scalars, check that they are formatted correctly and give an informative error message otherwise.

**Comment by khembach** [comment]
Maybe a little R script that would
• read the metadata file
• generate the design matrix
• generate the contrast matrix
• print out the design and contrast matrices to the console for checking
would be an option?
And provide sensible error messages in case of failure

Create a new rule that runs this script.
