### ISSUE TITLE
clarify how paths in config.yaml need to be specified

### ISSUE THREAD

**Issue by csoneson** [csoneson/ARMOR#66]
Unless we can find a good solution to allow relative paths, stress that all paths must be either absolute or relative to the location of the Snakefile.

**Comment by khembach** [comment]
It is described in the [wiki](https://github.com/csoneson/ARMOR/wiki/The-config.yaml-configuration-file) and in the `config.yaml` file. See cc5e4e37f50e6a1a5032a4d39b370fb005ef6b85
