### ISSUE TITLE
extend the checkinputs to check all inputs

### ISSUE THREAD

**Issue by fionarhuang** [csoneson/ARMOR#73]

**Comment by markrobinsonuzh** [comment]
- check that all necessary files - those in metadata file + reference - exist
- if run_camera: True, check that organism will work (is in msigdbr::msigdbr_show_species()) .. after removal of "_" from "organism: " variable.

**Comment by markrobinsonuzh** [comment]
https://github.com/csoneson/ARMOR/commit/26ee5d3fab7b0d31cb9b2bb6245927a1ddf8494a
