### ISSUE TITLE
CalledProcessError in EdgeR

### ISSUE THREAD

**Issue by devang-mehta** [csoneson/ARMOR#78]
Hi, I'm not sure what this means? I've previously run the workflow successfully with another dataset. In this case I'm getting the following error:
RuleException:
CalledProcessError in line 526 of /home/ruhrig/ARMOR/Snakefile:
Command 'source /home/ruhrig/miniconda3/bin/activate '/home/ruhrig/ARMOR/.snakemake/conda/17597c04'; set -euo pipefail;  R CMD BATCH --no-restore --no-save "--args se='/nfs/scratch/ARMOR-runs/williamsonout/outputR/tximeta_se.rds' organism='Homo_sapiens' design='~0+condition' contrast='UV_8_hr-Untreated,UV_24_hr-Untreated'  rmdtemplate='scripts/edgeR_dge.Rmd' outputdir='/nfs/scratch/ARMOR-runs/williamsonout/outputR' outputfile='edgeR_dge.html'" scripts/run_render.R /nfs/scratch/ARMOR-runs/williamsonout/Rout/run_dge_edgeR.Rout' returned non-zero exit status 1.
  File "/home/ruhrig/ARMOR/Snakefile", line 526, in __rule_edgeR
  File "/home/ruhrig/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
[Tue Mar 19 00:19:26 2019]
Finished job 9.
34 of 62 steps (55%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by markrobinsonuzh** [comment]
Can you give the output of the `williamsonout/Rout/run_dge_edgeR.Rout` file?

**Comment by devang-mehta** [comment]
R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> args <- (commandArgs(trailingOnly = TRUE))
> for (i in seq_len(length(args))) {
+     eval(parse(text = args[[i]]))
+ }
> 
> ## Mandatory arguments
> print(se)
[1] "/nfs/scratch/ARMOR-runs/williamsonout/outputR/tximeta_se.rds"
> print(rmdtemplate)
[1] "scripts/edgeR_dge.Rmd"
> print(outputdir)
[1] "/nfs/scratch/ARMOR-runs/williamsonout/outputR"
> print(outputfile)
[1] "edgeR_dge.html"
> 
> ## Arguments that are only used for some of the reports
> if (exists("organism")) {
+     print(organism)
+ } else {
+     organism <- NULL
+ }
[1] "Homo_sapiens"
> 
> if (exists("design")) {
+     print(design)
+ } else {
+     design <- NULL
+ }
[1] "~0+condition"
> 
> if (exists("contrast")) {
+     contrast <- strsplit(gsub(" ","",contrast), ",")[[1]]
+     print(contrast)
+ } else {
+     contrast <- NULL
+ }
[1] "UV_8_hr-Untreated"  "UV_24_hr-Untreated"
> 
> if (exists("genesets")) {
+     genesets <- strsplit(gsub(" ","",genesets), ",")[[1]]
+     print(genesets)
+ } else {
+     genesets <- NULL
+ }
> 
> if (exists("gtffile")) {
+     print(gtffile)
+ } else {
+     gtffile <- NULL
+ }
> 
> if (exists("bigwigdir")) {
+     bigwigdir <- normalizePath(bigwigdir)
+     print(bigwigdir)
+ } else {
+     bigwigdir <- NULL
+ }
> 
> source("scripts/generate_report.R")
> 
> generateReport(se = se, organism = organism, gtffile = gtffile,
+                contrast = contrast, design = design, genesets = genesets, 
+                bigwigdir = bigwigdir, rmdTemplate = rmdtemplate, 
+                outputDir = outputdir, outputFile = outputfile, 
+                forceOverwrite = TRUE, showCode = TRUE)
Quitting from lines 235-237 (edgeR_dge.Rmd) 
Error in eval(ej, envir = levelsenv) : object 'UV_8_hr' not found
Calls: generateReport ... eval -> as.data.frame -> makeContrasts -> eval -> eval
Execution halted

**Comment by devang-mehta** [comment]
And my metadata file is:
names	type	condition
SRR5097389	PE	UV_8_hr
SRR5097390	PE	UV_8_hr
SRR5097391	PE	UV_24_hr
SRR5097392	PE	UV_24_hr
SRR5097393	PE	Untreated
SRR5097394	PE	Untreated

**Comment by fionarhuang** [comment]
It might be helpful to run the rule `snakemake [--use-conda] checkinputs` to check whether the input in `config.yaml` file is correct before run the pipeline.

> oh, I realise it's a mistake in the contrast line of the config file. (forgot to prefix "condition" prior to UV_8_hr) apologies for the inconvenience.

It might be helpful to run the rule `snakemake [--use-conda] checkinputs` to check whether the input in `config.yaml` file is correct before run the pipeline.
