### ISSUE TITLE
Input exception wit SE reads

### ISSUE THREAD

**Issue by devang-mehta** [csoneson/ARMOR#79]
hi, for some reason my SE input is calling on trimgalorePE instead of SE?
Log:
Building DAG of jobs...
MissingInputException in line 297 of /home/ruhrig/ARMOR/Snakefile:
Missing input files for rule trimgalorePE:
/nfs/scratch/RNA-seq/Human/carrier/fastq/SRR3583291  SE  MCF7_control_None.fastq.gz

Metadata.txt:
names type  condition
SRR3583291  SE  MCF7_control
SRR3583292  SE  MCF7_RA
SRR3583293  SE  BT474_control
SRR3583294  SE  BT474_RA	

Config:
metatxt: /nfs/scratch/ARMOR-runs/metadata_carrier.txt
design: "~ 0 + condition"
contrast: conditionMCF7_RA-conditionMCF7_control,conditionBT474_RA-conditionBT474_control
genesets: H,C5
ncores: 7
FASTQ: /nfs/scratch/RNA-seq/Human/carrier/fastq
fqext1: 1
fqext2: 2
fqsuffix: fastq
output: /nfs/scratch/ARMOR-runs/carrierout
useCondaR: True
Rbin: R
run_trimming: True
run_STAR: True
run_DRIMSeq: True
run_camera: False

**Comment by csoneson** [comment]
Is your metadata text file tab-separated? It looks like it's taking the entire row as the sample name in `/nfs/scratch/RNA-seq/Human/carrier/fastq/SRR3583291 SE MCF7_control_None.fastq.gz`

**Comment by devang-mehta** [comment]
yes, that's what I thought too, but it is tab separated, and it's the same format that I used for PE runs that worked.

**Comment by devang-mehta** [comment]
> Is your metadata text file tab-separated? It looks like it's taking the entire row as the sample name in `/nfs/scratch/RNA-seq/Human/carrier/fastq/SRR3583291 SE MCF7_control_None.fastq.gz`

oh, double-checked and yes, apparently my texteditor is behaving strangely :)

**Comment by sorjuela** [comment]
Hi, might be useful to update your repo. We have added a couple of things that could be useful for you (more sanity checks) ;)

**Comment by devang-mehta** [comment]
> Hi, might be useful to update your repo. We have added a couple of things that could be useful for you (more sanity checks) ;)

hi, I tried to update the repo, but now I run into this error:
Error in rule pkginstall:
    jobid: 31
    output: example_data/output/Rout/pkginstall_state.txt
    log: example_data/output/Rout/install_pkgs.Rout
    conda-env: /home/ruhrig/ARMOR/.snakemake/conda/17597c04

RuleException:
CalledProcessError in line 93 of /home/ruhrig/ARMOR/Snakefile:
Command 'source /home/ruhrig/miniconda3/bin/activate '/home/ruhrig/ARMOR/.snakemake/conda/17597c04'; set -euo pipefail;  R CMD BATCH --no-restore --no-save "--args outtxt='example_data/output/Rout/pkginstall_state.txt' annotation='Ensembl' organism='Homo_sapiens'" scripts/install_pkgs.R example_data/output/Rout/install_pkgs.Rout' returned non-zero exit status 1.
  File "/home/ruhrig/ARMOR/Snakefile", line 93, in __rule_pkginstall
  File "/home/ruhrig/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Error! The Snakemake workflow aborted.
Complete log: /home/ruhrig/ARMOR/.snakemake/log/2019-03-20T140641.246857.snakemake.log

**Comment by csoneson** [comment]
Could you check the content of `example_data/output/Rout/install_pkgs.Rout` (see the [Troubleshooting](https://github.com/csoneson/ARMOR/wiki/Troubleshooting) guide)?

**Comment by devang-mehta** [comment]
this was the error:
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------

**Comment by csoneson** [comment]
Can you check that the R library is the right one? For example, that pulling down the updates did not overwrite the `.Renviron` file (if you changed that one).

**Comment by devang-mehta** [comment]
oh, i think it did. that file only contains:
R_LIBS_USER=""

**Comment by divy93** [comment]
hi, i am a new user of ARMOR, i got this error, how to tackle with this....
Error in rule pkginstall:
    jobid: 31
    output: example_data/output/Rout/pkginstall_state.txt
    log: example_data/output/Rout/install_pkgs.Rout (check log file(s) for error message)
    shell:
        R CMD BATCH --no-restore --no-save "--args outtxt='example_data/output/Rout/pkginstall_state.txt' ncores='1' annotation='Ensembl' organism='Homo_sapiens'" scripts/install_pkgs.R example_data/output/Rout/install_pkgs.Rout
        (exited with non-zero exit code)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Error! The Snakemake workflow aborted.

**Comment by markrobinsonuzh** [comment]
Hi @divy93,

You will probably find an error message at the bottom of `example_data/output/Rout/install_pkgs.Rout`. Please look at that and hopefully it will help you determine what to do.

See also the wiki about the multiple ways of "Managing software":
https://github.com/csoneson/ARMOR/wiki/Managing-software

Note: if that error has nothing to do with "Input exception with SE reads" (this issue), please start a new issue.

Mark
