### ISSUE TITLE
error in rule bigwig

### ISSUE THREAD

**Issue by rrdavis77** [csoneson/ARMOR#85]
When running ARMOR on some data I get an error when it is trying to generate the bigwig files.
`Error in rule bigwig:
    jobid: 51
    output: Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bw
    log: Jin/output/logs/bigwig_p63KO35.log (check log file(s) for error message)
    conda-env: /home/ryan/ARMOR/.snakemake/conda/74957150
    shell:
        echo 'bedtools version:
' > Jin/output/logs/bigwig_p63KO35.log; bedtools --version >> Jin/output/logs/bigwig_p63KO35.log; bedtools genomecov -split -ibam Jin/output/STAR/p63KO35/p63KO35_Aligned.sortedByCoord.out.bam -bg | sort -k1,1 -k2,2n > Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bedGraph; bedGraphToBigWig Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bedGraph /home/ryan/ARMOR/reference/human/STARIndex/Homo_sapiens.GRCh38.V30.STAR.idx/chrNameLength.txt Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bw; rm -f Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bedGraph`

In the terminal i see:
`Jin/output/STARbigwig/p63KO35_Aligned.sortedByCoord.out.bedGraph is not case-sensitive sorted at line 38881834.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.`

when looking at that specific line, we see:

`sed -n '38881833,38881835p' p63KO35_Aligned.sortedByCoord.out.bedGraph

chrY	57215886	57215994	1

GL000008.2	83526	83545	1

GL000008.2	85565	85566	1
`
I am using the Genome sequence, primary assembly (GRCh38) from gencode.

Not sure how to proceed.  Thanks!

**Comment by csoneson** [comment]
Not at a stable connection right now, but we do have `sort -k1,1 -k2,2n` in the `bigwig` rule, so it may be a problem with the `LC_COLLATE=C` part. Could you try to see whether adding `LC_COLLATE=C ` just before `sort` here helps: https://github.com/csoneson/ARMOR/blob/3bfc4033996fb61495b48c95e6064495a73c49b6/Snakefile#L471

**Comment by rrdavis77** [comment]
I'll add it and let you know if that solves it.
Thanks

**Comment by rrdavis77** [comment]
I changed the snake file line 471 by adding LC_COLLATE=C and it solved the issue.

` "bedtools genomecov -split -ibam {input.bam} -bg | LC_COLLATE=C sort -k1,1 -k2,2n > "`

**Comment by csoneson** [comment]
Great, thanks. We’ll fix that.
